# Generated by Django 3.2.9 on 2021-12-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='command',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.command'),
        ),
    ]
